export type Submission = {
  id: number;
  body?: string | null;
  url?: null;
  grade?: string | null;
  score?: number | null;
  submitted_at: string;
  assignment_id: number;
  user_id: number;
  submission_type: string;
  workflow_state: string;
  grade_matches_current_submission: boolean;
  graded_at?: string | null;
  grader_id?: number | null;
  attempt: number;
  cached_due_date?: null;
  excused?: boolean | null;
  late_policy_status?: null;
  points_deducted?: null;
  grading_period_id?: null;
  extra_attempts?: null;
  posted_at?: string | null;
  redo_request: boolean;
  custom_grade_status_id?: null;
  sticker?: null;
  late: boolean;
  missing: boolean;
  seconds_late: number;
  entered_grade?: string | null;
  entered_score?: number | null;
  attachments?: Attachment[] | null;
  preview_url?: string | null;
  anonymous_id: string;
};

export type Attachment = {
  id: number;
  uuid: string;
  folder_id: number;
  display_name: string;
  filename: string;
  upload_status: string;
  "content-type": string;
  url: string;
  size: number;
  created_at: string;
  updated_at: string;
  unlock_at?: null;
  locked: boolean;
  hidden: boolean;
  lock_at?: null;
  hidden_for_user: boolean;
  thumbnail_url: string;
  modified_at: string;
  mime_class: string;
  media_entry_id?: null;
  category: string;
  locked_for_user: boolean;
  preview_url?: null;
};
