build-docker-base:
    stage: 🐋 docker
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build . -t $BASE_IMAGE
        - docker push $BASE_IMAGE
    only:
        changes:
            - Dockerfile
            - .docker-ci.yml

build-docker-desktop:
    stage: 🐋 docker
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build . -f $DESKTOP_BASE_PATH/Dockerfile -t $DESKTOP_IMAGE
        - docker push $DESKTOP_IMAGE
    only:
        changes:
            - $DESKTOP_BASE_PATH/Dockerfile
            - .docker-ci.yml

build-docker-cli:
    stage: 🐋 docker
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build . -f $CLI_BASE_PATH/Dockerfile -t $CLI_IMAGE
        - docker push $CLI_IMAGE
    only:
        changes:
            - $CLI_BASE_PATH/Dockerfile
            - .docker-ci.yml
