import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //canvasDocSidebar: [{ type: 'autogenerated', dirName: '.' }],

    // But you can create a sidebar manually

    canvasDocSidebar: [
        {
            type: 'category',
            label: 'Getting Started',
            items: ['Getting Started/Overview', 'Getting Started/Quickstart'],
        },
        {
            type: 'category',
            label: 'CLI',
            items: ['CLI/Overview', 'CLI/Quickstart', 'CLI/Deploy'],
        },
        {
            type: 'category',
            label: 'Desktop',
            items: ['Desktop/Overview', 'Desktop/Quickstart', 'Desktop/Deploy'],
        },
        {
            type: 'category',
            label: 'Docs Site',
            items: ['Docs/Overview', 'Docs/Quickstart', 'Docs/Deploy'],
        },
    ],

    testingSidebar: [
        {
            type: 'category',
            label: 'CLI-Test',
            items: ['Testing/CLI/CourseSelect', 'Testing/CLI/AssignmentSelect'],
        },
        {
            type: 'category',
            label: 'Desktop-Test',
            items: [
                'Testing/Desktop/Homepage',
                'Testing/Desktop/Settingspage',
                'Testing/Desktop/CourseSelect',
                'Testing/Desktop/AssignmentSelect',
            ],
        },
    ],
}

export default sidebars
