FROM rust:1.73.0

RUN apt-get update
RUN apt-get install -y curl

# Install Node.js 18.x
RUN curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
RUN chmod 500 nsolid_setup_deb.sh
RUN ./nsolid_setup_deb.sh 18
RUN apt-get install nodejs -y