FROM electronuserland/builder:latest

WORKDIR /usr/src/app

# Install dependencies
COPY ../apps/desktop/package-lock.json .

RUN npm ci

# Copy source code
COPY ../apps/desktop .

# Build the app
RUN npm run build:linux
