# This file is used to build the Windows Docker image for the desktop application.
FROM mcr.microsoft.com/windows/servercore:ltsc2022-amd64

# Install Chocolatey (hopefully)
RUN powershell Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
RUN choco