import { describe, test, expect } from 'vitest'

import {
    handleDates,
    intercept,
    getApiHeaders,
    getCourses,
    getAssignments,
    getAssignmentsWithCourseId,
    getSubmissions,
    getQuiz,
    getQuizSubmission,
} from '../canvas.api'

describe('testToJSON', () => {
    const sampleRawJSON = '{"color1":"Blue","numColors":1, "hasColors": true}'
    const sampleOptions = { status: 200, statusText: 'OK' }
    const sampleResponse = new Response(sampleRawJSON, sampleOptions)

    test('toJSON test', async () => {
        const correctJSON = { color1: 'Blue', numColors: 1, hasColors: true }
        const recievedJSON = await sampleResponse.json()
        expect(recievedJSON).toEqual(correctJSON)
    })
})

describe('Testing handleDates function', () => {
    const inputHandleDates = {
        date1: '2024-04-17T08:30:00Z',
        date2: '2024-04-18T12:45:00Z',
        nested: {
            date3: '2024-04-19T15:20:00Z',
            nested2: {
                date4: '2024-04-20T18:10:00Z',
                nonDate: 'This is not a date string',
            },
        },
        nonDate: 'This is also not a date string',
    }

    const expectedOutput = {
        date1: new Date('2024-04-17T08:30:00Z'),
        date2: new Date('2024-04-18T12:45:00Z'),
        nested: {
            date3: new Date('2024-04-19T15:20:00Z'),
            nested2: {
                date4: new Date('2024-04-20T18:10:00Z'),
                nonDate: 'This is not a date string',
            },
        },
        nonDate: 'This is also not a date string',
    }

    test('handleDates test', () => {
        //act
        handleDates(inputHandleDates)

        //assert for all cases
        expect(inputHandleDates).toEqual(expectedOutput)
        expect(handleDates(null)).toBe(undefined)
        expect(handleDates(undefined)).toBe(undefined)
    })
})

describe('Testing intercept', () => {
    const sampleRawJSON =
        '{"color1":"Blue","numColors":1, "hasColors": true, "date": "2024-04-17T08:30:00Z"}'
    const sampleOptions = { status: 200, statusText: 'OK' }
    const sampleResponse = new Response(sampleRawJSON, sampleOptions)
    //intercept(sampleRawJSON)

    test('intercept Test', async () => {
        const expectedResponse = intercept(sampleResponse)
        //expect(sampleResponse).toEqual(expectedResponse)
        console.log(sampleResponse)
        console.log(expectedResponse)
    })
})

describe('Testing getApiHeaders', () => {
    const sampleHeaders: HeadersInit = {
        head1: 'value1',
        head2: 'value2',
    }
    const sampleAccessToken = '1234567890qwertyuiopasdfghjklzxcvbnm'
    const expectedHeaders = {
        Authorization: 'Bearer ' + sampleAccessToken,
        head1: 'value1',
        head2: 'value2',
    }
    test('getApiHeaders test', () => {
        const recievedHeaders = getApiHeaders(
            { accessToken: sampleAccessToken },
            sampleHeaders
        )
        console.log(recievedHeaders)
        console.log(expectedHeaders)
        expect(recievedHeaders).toEqual(expectedHeaders)
    })
})

describe('Testing getCourses', () => {
    // const sampleHeaders: Record<string, string> = {
    //     'Content-Type': 'application/json',
    //     'Authorization': 'Bearer <token>'
    // };
    const coursesJSONList = [
        {
            id: 3,
            name: 'No Assignments',
            account_id: 3,
            uuid: 'EwNcb4VPhT1lXxFBTQIDVgwWOLGMFSSyu04Ha43Y',
            start_at: null,
            grading_standard_id: null,
            is_public: false,
            created_at: '2024-01-19T17:44:27Z',
            course_code: 'NoAssignments',
            default_view: 'assignments',
            root_account_id: 2,
            enrollment_term_id: 3,
            license: 'private',
            grade_passback_setting: null,
            end_at: null,
            public_syllabus: false,
            public_syllabus_to_auth: false,
            storage_quota_mb: 500,
            is_public_to_auth_users: false,
            homeroom_course: false,
            course_color: null,
            friendly_name: null,
            apply_assignment_group_weights: false,
            calendar: {
                ics: 'http://sdlstudentvm06.msoe.edu/feeds/calendars/course_EwNcb4VPhT1lXxFBTQIDVgwWOLGMFSSyu04Ha43Y.ics',
            },
            time_zone: 'America/Denver',
            blueprint: false,
            sis_course_id: null,
            sis_import_id: null,
            integration_id: null,
            enrollments: [
                {
                    type: 'teacher',
                    role: 'TeacherEnrollment',
                    role_id: 20,
                    user_id: 1,
                    enrollment_state: 'active',
                    limit_privileges_to_course_section: false,
                },
            ],
            hide_final_grades: false,
            workflow_state: 'available',
            restrict_enrollments_to_course_dates: false,
        },
        {
            id: 1,
            name: 'Test Course 1',
            account_id: 3,
            uuid: 'dZdmGkWRxU8pYyJaNnW60M2mYIQ1HmWAK4Wg06mc',
            start_at: null,
            grading_standard_id: null,
            is_public: null,
            created_at: '2023-09-20T14:29:51Z',
            course_code: 'TST1',
            default_view: 'syllabus',
            root_account_id: 2,
            enrollment_term_id: 3,
            license: null,
            grade_passback_setting: null,
            end_at: null,
            public_syllabus: false,
            public_syllabus_to_auth: false,
            storage_quota_mb: 500,
            is_public_to_auth_users: false,
            homeroom_course: false,
            course_color: null,
            friendly_name: null,
            apply_assignment_group_weights: false,
            calendar: {
                ics: 'http://sdlstudentvm06.msoe.edu/feeds/calendars/course_dZdmGkWRxU8pYyJaNnW60M2mYIQ1HmWAK4Wg06mc.ics',
            },
            time_zone: 'America/Denver',
            blueprint: false,
            sis_course_id: null,
            sis_import_id: null,
            integration_id: null,
            enrollments: [
                {
                    type: 'teacher',
                    role: 'TeacherEnrollment',
                    role_id: 20,
                    user_id: 1,
                    enrollment_state: 'active',
                    limit_privileges_to_course_section: false,
                },
            ],
            hide_final_grades: false,
            workflow_state: 'available',
            restrict_enrollments_to_course_dates: false,
        },
        {
            id: 2,
            name: 'Test Course 2',
            account_id: 2,
            uuid: 'vWzOKMFCiCgweeHqYHwGKcCiv2cEVhs4sJ1hROMn',
            start_at: null,
            grading_standard_id: null,
            is_public: null,
            created_at: '2023-09-25T13:47:29Z',
            course_code: 'TST2',
            default_view: 'modules',
            root_account_id: 2,
            enrollment_term_id: 3,
            license: null,
            grade_passback_setting: null,
            end_at: null,
            public_syllabus: false,
            public_syllabus_to_auth: false,
            storage_quota_mb: 500,
            is_public_to_auth_users: false,
            homeroom_course: false,
            course_color: null,
            friendly_name: null,
            apply_assignment_group_weights: false,
            calendar: {
                ics: 'http://sdlstudentvm06.msoe.edu/feeds/calendars/course_vWzOKMFCiCgweeHqYHwGKcCiv2cEVhs4sJ1hROMn.ics',
            },
            time_zone: 'America/Denver',
            blueprint: false,
            sis_course_id: null,
            sis_import_id: null,
            integration_id: null,
            enrollments: [
                {
                    type: 'teacher',
                    role: 'TeacherEnrollment',
                    role_id: 20,
                    user_id: 1,
                    enrollment_state: 'active',
                    limit_privileges_to_course_section: false,
                },
            ],
            hide_final_grades: false,
            workflow_state: 'available',
            restrict_enrollments_to_course_dates: false,
        },
        {
            id: 4,
            name: 'This has a plus++',
            account_id: 3,
            uuid: 'KlfbeJNzS55Ca9plcX9kWOcPZ0n2Gjo4b8UUrDCK',
            start_at: null,
            grading_standard_id: null,
            is_public: false,
            created_at: '2024-04-03T16:09:47Z',
            course_code: 'This',
            default_view: 'assignments',
            root_account_id: 2,
            enrollment_term_id: 3,
            license: 'private',
            grade_passback_setting: null,
            end_at: null,
            public_syllabus: false,
            public_syllabus_to_auth: false,
            storage_quota_mb: 500,
            is_public_to_auth_users: false,
            homeroom_course: false,
            course_color: null,
            friendly_name: null,
            apply_assignment_group_weights: false,
            calendar: {
                ics: 'http://sdlstudentvm06.msoe.edu/feeds/calendars/course_KlfbeJNzS55Ca9plcX9kWOcPZ0n2Gjo4b8UUrDCK.ics',
            },
            time_zone: 'America/Denver',
            blueprint: false,
            sis_course_id: null,
            sis_import_id: null,
            integration_id: null,
            enrollments: [
                {
                    type: 'teacher',
                    role: 'TeacherEnrollment',
                    role_id: 20,
                    user_id: 1,
                    enrollment_state: 'active',
                    limit_privileges_to_course_section: false,
                },
            ],
            hide_final_grades: false,
            workflow_state: 'available',
            restrict_enrollments_to_course_dates: false,
        },
    ]

    test('getCourses Test', async () => {
        const response = await getCourses({
            canvasAccessToken:
                'reK0qt1RHGt1tCVrNwrNasbWnOd8T52y2vW4BV3yM1mXZ9jtLAXU6Xn2mtzcNZ3B',
            canvasDomain: 'http://sdlstudentvm06.msoe.edu',
        })
        expect(response).toEqual(coursesJSONList)

        // const response = await fetch('https://example.com/user')
        // const user = await response.json()
        // console.log(user)
    })
})

describe('Testing getAssignments', async () => {
    const assignmentsJSONList = [
        {
            id: 1,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 5.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:38:53Z',
            updated_at: '2023-09-20T14:40:04Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 1,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImQwN2MzOTcyLTk4NWMtNDA1Ny05OTIyLWQ2M2I0ZDdkYTZlYSJ9.aqOTa7APBGkay2nFSyE3dGcKjvycszkhIr50xHbH0mw',
            lti_context_id: 'd07c3972-985c-4057-9922-d63b4d7da6ea',
            course_id: 1,
            name: 'Test Assignment 1',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: false,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/1',
            has_overrides: false,
            needs_grading_count: 1,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/1/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 2,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 5.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:45:32Z',
            updated_at: '2023-09-20T14:46:48Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 2,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImUwMzNlNDU3LWFmYzItNDhlMS05MmI2LTkyNDg4Mzc0OGQ2OSJ9.BTXhoTHyK0vw24YTHsmYan9LJwQGEcvaC5UKAqVVSYo',
            lti_context_id: 'e033e457-afc2-48e1-92b6-924883748d69',
            course_id: 1,
            name: 'Test Rubric',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: false,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/2',
            has_overrides: false,
            needs_grading_count: 1,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            use_rubric_for_grading: false,
            free_form_criterion_comments: false,
            rubric: [
                {
                    id: '_9349',
                    points: 5.0,
                    description: 'Description of criterion',
                    long_description: 'Neet',
                    criterion_use_range: false,
                    ratings: [
                        {
                            id: 'blank',
                            points: 5.0,
                            description: 'Full Marks',
                            long_description: '',
                        },
                        {
                            id: '1_8062',
                            points: 1.0,
                            description: 'djlflds',
                            long_description: '',
                        },
                        {
                            id: 'blank_2',
                            points: 0.0,
                            description: 'No Marks',
                            long_description: '',
                        },
                    ],
                },
            ],
            rubric_settings: {
                id: 1,
                title: 'Some Rubric',
                points_possible: 5.0,
                free_form_criterion_comments: false,
                hide_score_total: false,
                hide_points: false,
            },
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/2/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 3,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 5.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:50:34Z',
            updated_at: '2024-04-05T02:32:46Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 3,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjM5YWVjNGNiLTZjNjEtNDM2Ni1iMTMzLTI1ODlhYmFmMDcxMyJ9.Ln2nOuv3lro9rDZNOBP266Hhy0tRn0lvNwtpTmo42ag',
            lti_context_id: '39aec4cb-6c61-4366-b133-2589abaf0713',
            course_id: 1,
            name: 'File',
            submission_types: ['online_upload'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/3',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/3/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 4,
            description:
                '\u003cp\u003eThis is the Description -patrick\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 2.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:54:49Z',
            updated_at: '2024-02-08T07:05:31Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 4,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjY1MzY1ZjUzLTIzOTgtNDIyNy05N2MzLWFiNWZlMmYxMTIwZCIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVRoaXMgaXMgdGhlIERlc2NyaXB0aW9uIC1wYXRyaWNrXHUwMDNjL3BcdTAwM2UifQ.tX0zBVQp_Yi326FcBGFVEXfPwAqz4CAifvnzG_EePNY',
            lti_context_id: '65365f53-2398-4227-97c3-ab5fe2f1120d',
            course_id: 1,
            name: 'Unnamed Quiz',
            submission_types: ['online_quiz'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: true,
            can_duplicate: false,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: false,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/4',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            quiz_id: 1,
            anonymous_submissions: false,
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/quizzes/1/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 6,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-01-19T18:39:35Z',
            updated_at: '2024-01-19T18:39:35Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 5,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImVhOGVhODc4LWZlMzctNGJjNy04YTFhLWI2ZjYzOWVmMWUxOSJ9.v678Q-Qnpd9-gP4byiAXVJ0SgEsdAzEdK53AKw6_7P4',
            lti_context_id: 'ea8ea878-fe37-4bc7-8a1a-b6f639ef1e19',
            course_id: 1,
            name: 'No Submissions',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: false,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/6',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: true,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/6/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 11,
            description:
                '\u003cp\u003eA URL submission assignment.\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-05T03:03:16Z',
            updated_at: '2024-04-05T03:03:16Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 6,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjgxMDE0Y2FkLTFhYjEtNDQ1My1hOTdiLTFiNDM2YzliYzYzMSIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZUEgVVJMIHN1Ym1pc3Npb24gYXNzaWdubWVudC5cdTAwM2MvcFx1MDAzZSJ9.QMXdv8dNU9x8J8uIx2TnuFP-vvdvadK2Uv4i4jEsTy4',
            lti_context_id: '81014cad-1ab1-4453-a97b-1b436c9bc631',
            course_id: 1,
            name: 'URL',
            submission_types: ['online_url'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/11',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/11/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 12,
            description:
                '\u003ch1\u003eThis is a heading\u003c/h1\u003e\n\u003cp\u003e\u003ca href="https://lobste.rs"\u003elobsters link\u003c/a\u003e\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-05T03:23:43Z',
            updated_at: '2024-04-05T03:23:43Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 7,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjQ2YWRlNDFhLTVhNDYtNGU2MC1iN2RlLTRhMTUyOGY3MTVkYiIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjaDFcdTAwM2VUaGlzIGlzIGEgaGVhZGluZ1x1MDAzYy9oMVx1MDAzZVxuXHUwMDNjcFx1MDAzZVx1MDAzY2EgaHJlZj1cImh0dHBzOi8vbG9ic3RlLnJzXCJcdTAwM2Vsb2JzdGVycyBsaW5rXHUwMDNjL2FcdTAwM2VcdTAwM2MvcFx1MDAzZSJ9.aI37iCmnifEBiYuV6Yos7IV9tCdWsM0POi50fGQTyQ0',
            lti_context_id: '46ade41a-5a46-4e60-b7de-4a1528f715db',
            course_id: 1,
            name: 'HTML Assignment',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/12',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/12/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 13,
            description: '\u003cp\u003eWhat is this?\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-08T14:21:24Z',
            updated_at: '2024-04-08T14:21:24Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 8,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: 13,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjM0NzlkYjlmLTMwZjQtNGMwMC1iNzAzLTFmNzAwODdhNjg0NyIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVdoYXQgaXMgdGhpcz9cdTAwM2MvcFx1MDAzZSJ9.9PzBVgBUkzUiCP1pzFCqs55k4dS0AMGvZm6n_9Nf5ZY',
            lti_context_id: '3479db9f-30f4-4c00-b703-1f70087a6847',
            course_id: 1,
            name: 'Student Annotation',
            submission_types: ['student_annotation'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/13',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/13/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 14,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-10T13:30:53Z',
            updated_at: '2024-04-10T13:33:48Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 9,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjAxMTg1ZDI2LWQyYjMtNDFhYS1hZGI4LTk4MGRjNDc2ODBjMSJ9.KR91EU7irT6VT6Zqut0G9mX5AicCTtT0K89RD12NoYo',
            lti_context_id: '01185d26-d2b3-41aa-adb8-980dc47680c1',
            course_id: 1,
            name: 'Media Submission',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: false,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/14',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: true,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/14/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
    ]

    test('getAssignments Test', async () => {
        const response = await getAssignments({
            canvasAccessToken: 'Fake Token',
            canvasDomain: 'http://sdlstudentvm06.msoe.edu',
            courseId: 1,
        })
        expect(response).toEqual(assignmentsJSONList)
    })
})

describe('Testing getAssignments with courseid', async () => {
    const assignmentsJSONList = [
        {
            id: 1,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 5.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:38:53Z',
            updated_at: '2023-09-20T14:40:04Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 1,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImQwN2MzOTcyLTk4NWMtNDA1Ny05OTIyLWQ2M2I0ZDdkYTZlYSJ9.aqOTa7APBGkay2nFSyE3dGcKjvycszkhIr50xHbH0mw',
            lti_context_id: 'd07c3972-985c-4057-9922-d63b4d7da6ea',
            course_id: 1,
            name: 'Test Assignment 1',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: false,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/1',
            has_overrides: false,
            needs_grading_count: 1,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/1/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 2,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 5.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:45:32Z',
            updated_at: '2023-09-20T14:46:48Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 2,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImUwMzNlNDU3LWFmYzItNDhlMS05MmI2LTkyNDg4Mzc0OGQ2OSJ9.BTXhoTHyK0vw24YTHsmYan9LJwQGEcvaC5UKAqVVSYo',
            lti_context_id: 'e033e457-afc2-48e1-92b6-924883748d69',
            course_id: 1,
            name: 'Test Rubric',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: false,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/2',
            has_overrides: false,
            needs_grading_count: 1,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            use_rubric_for_grading: false,
            free_form_criterion_comments: false,
            rubric: [
                {
                    id: '_9349',
                    points: 5.0,
                    description: 'Description of criterion',
                    long_description: 'Neet',
                    criterion_use_range: false,
                    ratings: [
                        {
                            id: 'blank',
                            points: 5.0,
                            description: 'Full Marks',
                            long_description: '',
                        },
                        {
                            id: '1_8062',
                            points: 1.0,
                            description: 'djlflds',
                            long_description: '',
                        },
                        {
                            id: 'blank_2',
                            points: 0.0,
                            description: 'No Marks',
                            long_description: '',
                        },
                    ],
                },
            ],
            rubric_settings: {
                id: 1,
                title: 'Some Rubric',
                points_possible: 5.0,
                free_form_criterion_comments: false,
                hide_score_total: false,
                hide_points: false,
            },
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/2/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 3,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 5.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:50:34Z',
            updated_at: '2024-04-05T02:32:46Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 3,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjM5YWVjNGNiLTZjNjEtNDM2Ni1iMTMzLTI1ODlhYmFmMDcxMyJ9.Ln2nOuv3lro9rDZNOBP266Hhy0tRn0lvNwtpTmo42ag',
            lti_context_id: '39aec4cb-6c61-4366-b133-2589abaf0713',
            course_id: 1,
            name: 'File',
            submission_types: ['online_upload'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/3',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/3/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 4,
            description:
                '\u003cp\u003eThis is the Description -patrick\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 2.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2023-09-20T14:54:49Z',
            updated_at: '2024-02-08T07:05:31Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 4,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjY1MzY1ZjUzLTIzOTgtNDIyNy05N2MzLWFiNWZlMmYxMTIwZCIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVRoaXMgaXMgdGhlIERlc2NyaXB0aW9uIC1wYXRyaWNrXHUwMDNjL3BcdTAwM2UifQ.tX0zBVQp_Yi326FcBGFVEXfPwAqz4CAifvnzG_EePNY',
            lti_context_id: '65365f53-2398-4227-97c3-ab5fe2f1120d',
            course_id: 1,
            name: 'Unnamed Quiz',
            submission_types: ['online_quiz'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: true,
            can_duplicate: false,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: false,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/4',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            quiz_id: 1,
            anonymous_submissions: false,
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/quizzes/1/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 6,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-01-19T18:39:35Z',
            updated_at: '2024-01-19T18:39:35Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 5,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6ImVhOGVhODc4LWZlMzctNGJjNy04YTFhLWI2ZjYzOWVmMWUxOSJ9.v678Q-Qnpd9-gP4byiAXVJ0SgEsdAzEdK53AKw6_7P4',
            lti_context_id: 'ea8ea878-fe37-4bc7-8a1a-b6f639ef1e19',
            course_id: 1,
            name: 'No Submissions',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: false,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/6',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: true,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/6/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 11,
            description:
                '\u003cp\u003eA URL submission assignment.\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-05T03:03:16Z',
            updated_at: '2024-04-05T03:03:16Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 6,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjgxMDE0Y2FkLTFhYjEtNDQ1My1hOTdiLTFiNDM2YzliYzYzMSIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZUEgVVJMIHN1Ym1pc3Npb24gYXNzaWdubWVudC5cdTAwM2MvcFx1MDAzZSJ9.QMXdv8dNU9x8J8uIx2TnuFP-vvdvadK2Uv4i4jEsTy4',
            lti_context_id: '81014cad-1ab1-4453-a97b-1b436c9bc631',
            course_id: 1,
            name: 'URL',
            submission_types: ['online_url'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/11',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/11/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 12,
            description:
                '\u003ch1\u003eThis is a heading\u003c/h1\u003e\n\u003cp\u003e\u003ca href="https://lobste.rs"\u003elobsters link\u003c/a\u003e\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-05T03:23:43Z',
            updated_at: '2024-04-05T03:23:43Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 7,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjQ2YWRlNDFhLTVhNDYtNGU2MC1iN2RlLTRhMTUyOGY3MTVkYiIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjaDFcdTAwM2VUaGlzIGlzIGEgaGVhZGluZ1x1MDAzYy9oMVx1MDAzZVxuXHUwMDNjcFx1MDAzZVx1MDAzY2EgaHJlZj1cImh0dHBzOi8vbG9ic3RlLnJzXCJcdTAwM2Vsb2JzdGVycyBsaW5rXHUwMDNjL2FcdTAwM2VcdTAwM2MvcFx1MDAzZSJ9.aI37iCmnifEBiYuV6Yos7IV9tCdWsM0POi50fGQTyQ0',
            lti_context_id: '46ade41a-5a46-4e60-b7de-4a1528f715db',
            course_id: 1,
            name: 'HTML Assignment',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/12',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/12/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 13,
            description: '\u003cp\u003eWhat is this?\u003c/p\u003e',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-08T14:21:24Z',
            updated_at: '2024-04-08T14:21:24Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 8,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: 13,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjM0NzlkYjlmLTMwZjQtNGMwMC1iNzAzLTFmNzAwODdhNjg0NyIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVdoYXQgaXMgdGhpcz9cdTAwM2MvcFx1MDAzZSJ9.9PzBVgBUkzUiCP1pzFCqs55k4dS0AMGvZm6n_9Nf5ZY',
            lti_context_id: '3479db9f-30f4-4c00-b703-1f70087a6847',
            course_id: 1,
            name: 'Student Annotation',
            submission_types: ['student_annotation'],
            has_submitted_submissions: true,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: true,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/13',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: false,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/13/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
        {
            id: 14,
            description: '',
            due_at: null,
            unlock_at: null,
            lock_at: null,
            points_possible: 10.0,
            grading_type: 'points',
            assignment_group_id: 1,
            grading_standard_id: null,
            created_at: '2024-04-10T13:30:53Z',
            updated_at: '2024-04-10T13:33:48Z',
            peer_reviews: false,
            automatic_peer_reviews: false,
            position: 9,
            grade_group_students_individually: false,
            anonymous_peer_reviews: false,
            group_category_id: null,
            post_to_sis: false,
            moderated_grading: false,
            omit_from_final_grade: false,
            intra_group_peer_reviews: false,
            anonymous_instructor_annotations: false,
            anonymous_grading: false,
            graders_anonymous_to_graders: false,
            grader_count: 0,
            grader_comments_visible_to_graders: true,
            final_grader_id: null,
            grader_names_visible_to_final_grader: true,
            allowed_attempts: -1,
            annotatable_attachment_id: null,
            hide_in_gradebook: false,
            secure_params:
                'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjAxMTg1ZDI2LWQyYjMtNDFhYS1hZGI4LTk4MGRjNDc2ODBjMSJ9.KR91EU7irT6VT6Zqut0G9mX5AicCTtT0K89RD12NoYo',
            lti_context_id: '01185d26-d2b3-41aa-adb8-980dc47680c1',
            course_id: 1,
            name: 'Media Submission',
            submission_types: ['online_text_entry'],
            has_submitted_submissions: false,
            due_date_required: false,
            max_name_length: 255,
            in_closed_grading_period: false,
            graded_submissions_exist: false,
            is_quiz_assignment: false,
            can_duplicate: true,
            original_course_id: null,
            original_assignment_id: null,
            original_lti_resource_link_id: null,
            original_assignment_name: null,
            original_quiz_id: null,
            workflow_state: 'published',
            important_dates: false,
            muted: true,
            html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/14',
            has_overrides: false,
            needs_grading_count: 0,
            sis_assignment_id: null,
            integration_id: null,
            integration_data: {},
            published: true,
            unpublishable: true,
            only_visible_to_overrides: false,
            locked_for_user: false,
            submissions_download_url:
                'http://sdlstudentvm06.msoe.edu/courses/1/assignments/14/submissions?zip=1',
            post_manually: false,
            anonymize_students: false,
            require_lockdown_browser: false,
            restrict_quantitative_data: false,
        },
    ]

    test('Testing getAssignmentsWithCourseId', async () => {
        console.log('hello')
        const response = await getAssignmentsWithCourseId({
            canvasAccessToken: 'Fake Token',
            canvasDomain: 'http://sdlstudentvm06.msoe.edu',
            courseId: 1,
        })
        // console.log(response)
        // console.log("______________________________")
        // console.log(assignmentsJSONList)
        expect(response.assignments).toEqual(assignmentsJSONList)
        expect(response.courseId).toEqual(1)
    })
})

describe('Testing getSubmissions', async () => {
    const submissionsJSONList = [
        [
            {
                id: 4,
                body: 'user: 2, quiz: 1, score: 1.0, time: 2023-10-18 14:04:23 +0000',
                url: null,
                grade: '1',
                score: 1.0,
                submitted_at: '2023-09-21T03:39:56Z',
                assignment_id: 4,
                user_id: 2,
                submission_type: 'online_quiz',
                workflow_state: 'graded',
                grade_matches_current_submission: true,
                graded_at: '2024-02-06T00:29:19Z',
                grader_id: 1,
                attempt: 1,
                cached_due_date: null,
                excused: null,
                late_policy_status: null,
                points_deducted: null,
                grading_period_id: null,
                extra_attempts: null,
                posted_at: '2023-09-21T03:39:56Z',
                redo_request: false,
                custom_grade_status_id: null,
                sticker: null,
                late: false,
                missing: false,
                seconds_late: 0,
                entered_grade: '1',
                entered_score: 1.0,
                preview_url:
                    'http://sdlstudentvm06.msoe.edu/courses/1/assignments/4/submissions/2?preview=1\u0026version=1',
                submission_comments: [
                    {
                        id: 4,
                        comment: 'Overall Comment for Test User 1',
                        author_id: 1,
                        author_name: 'brands@msoe.edu',
                        created_at: '2024-02-06T01:28:28Z',
                        edited_at: null,
                        attempt: null,
                        author: {
                            id: 1,
                            anonymous_id: '1',
                            display_name: 'brands@msoe.edu',
                            avatar_image_url:
                                'http://canvas.instructure.com/images/messages/avatar-50.png',
                            html_url:
                                'http://sdlstudentvm06.msoe.edu/courses/1/users/1',
                            pronouns: null,
                        },
                    },
                ],
                anonymous_id: 'fStKz',
            },
            {
                id: 14,
                body: 'user: 4, quiz: 1, score: 0.0, time: 2024-02-08 07:05:31 +0000',
                url: null,
                grade: '0',
                score: 0.0,
                submitted_at: '2024-02-08T07:05:31Z',
                assignment_id: 4,
                user_id: 4,
                submission_type: 'online_quiz',
                workflow_state: 'graded',
                grade_matches_current_submission: true,
                graded_at: '2024-02-08T07:05:31Z',
                grader_id: -1,
                attempt: 1,
                cached_due_date: null,
                excused: null,
                late_policy_status: null,
                points_deducted: null,
                grading_period_id: null,
                extra_attempts: null,
                posted_at: '2024-02-08T07:05:31Z',
                redo_request: false,
                custom_grade_status_id: null,
                sticker: null,
                late: false,
                missing: false,
                seconds_late: 0,
                entered_grade: '0',
                entered_score: 0.0,
                preview_url:
                    'http://sdlstudentvm06.msoe.edu/courses/1/assignments/4/submissions/4?preview=1\u0026version=1',
                submission_comments: [],
                anonymous_id: 'RUSa6',
            },
            {
                id: 19,
                body: 'user: 5, quiz: 1, score: 2.0, time: 2024-02-06 01:36:00 +0000',
                url: null,
                grade: '2',
                score: 2.0,
                submitted_at: '2024-02-06T01:36:00Z',
                assignment_id: 4,
                user_id: 5,
                submission_type: 'online_quiz',
                workflow_state: 'graded',
                grade_matches_current_submission: true,
                graded_at: '2024-02-06T01:36:00Z',
                grader_id: -1,
                attempt: 1,
                cached_due_date: null,
                excused: null,
                late_policy_status: null,
                points_deducted: null,
                grading_period_id: null,
                extra_attempts: null,
                posted_at: '2024-02-06T01:36:00Z',
                redo_request: false,
                custom_grade_status_id: null,
                sticker: null,
                late: false,
                missing: false,
                seconds_late: 0,
                entered_grade: '2',
                entered_score: 2.0,
                preview_url:
                    'http://sdlstudentvm06.msoe.edu/courses/1/assignments/4/submissions/5?preview=1\u0026version=1',
                submission_comments: [
                    {
                        id: 5,
                        comment: 'Overall Comment Test User 2',
                        author_id: 1,
                        author_name: 'brands@msoe.edu',
                        created_at: '2024-02-06T01:36:42Z',
                        edited_at: null,
                        attempt: null,
                        author: {
                            id: 1,
                            anonymous_id: '1',
                            display_name: 'brands@msoe.edu',
                            avatar_image_url:
                                'http://canvas.instructure.com/images/messages/avatar-50.png',
                            html_url:
                                'http://sdlstudentvm06.msoe.edu/courses/1/users/1',
                            pronouns: null,
                        },
                    },
                ],
                anonymous_id: 'nq3W6',
            },
        ],
    ]

    test('Testing getSubmissions', async () => {
        const response = await getSubmissions({
            canvasAccessToken: 'Fake Token',
            canvasDomain: 'http://sdlstudentvm06.msoe.edu',
            courseId: 1,
            assignmentId: 4,
            isStudent: false,
        })
        expect(response).toEqual(submissionsJSONList)
        // NEED TO ADD IS STUDENT FUNCTIONALITY
    })
})

describe('Testing getQuiz', async () => {
    const quizJSONList = {
        id: 4,
        description:
            '\u003cp\u003eThis is the Description -patrick\u003c/p\u003e',
        due_at: null,
        unlock_at: null,
        lock_at: null,
        points_possible: 2.0,
        grading_type: 'points',
        assignment_group_id: 1,
        grading_standard_id: null,
        created_at: '2023-09-20T14:54:49Z',
        updated_at: '2024-02-08T07:05:31Z',
        peer_reviews: false,
        automatic_peer_reviews: false,
        position: 4,
        grade_group_students_individually: false,
        anonymous_peer_reviews: false,
        group_category_id: null,
        post_to_sis: false,
        moderated_grading: false,
        omit_from_final_grade: false,
        intra_group_peer_reviews: false,
        anonymous_instructor_annotations: false,
        anonymous_grading: false,
        graders_anonymous_to_graders: false,
        grader_count: 0,
        grader_comments_visible_to_graders: true,
        final_grader_id: null,
        grader_names_visible_to_final_grader: true,
        allowed_attempts: -1,
        annotatable_attachment_id: null,
        hide_in_gradebook: false,
        secure_params:
            'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsdGlfYXNzaWdubWVudF9pZCI6IjY1MzY1ZjUzLTIzOTgtNDIyNy05N2MzLWFiNWZlMmYxMTIwZCIsImx0aV9hc3NpZ25tZW50X2Rlc2NyaXB0aW9uIjoiXHUwMDNjcFx1MDAzZVRoaXMgaXMgdGhlIERlc2NyaXB0aW9uIC1wYXRyaWNrXHUwMDNjL3BcdTAwM2UifQ.tX0zBVQp_Yi326FcBGFVEXfPwAqz4CAifvnzG_EePNY',
        lti_context_id: '65365f53-2398-4227-97c3-ab5fe2f1120d',
        course_id: 1,
        name: 'Unnamed Quiz',
        submission_types: ['online_quiz'],
        has_submitted_submissions: true,
        due_date_required: false,
        max_name_length: 255,
        in_closed_grading_period: false,
        graded_submissions_exist: true,
        is_quiz_assignment: true,
        can_duplicate: false,
        original_course_id: null,
        original_assignment_id: null,
        original_lti_resource_link_id: null,
        original_assignment_name: null,
        original_quiz_id: null,
        workflow_state: 'published',
        important_dates: false,
        muted: false,
        html_url: 'http://sdlstudentvm06.msoe.edu/courses/1/assignments/4',
        has_overrides: false,
        needs_grading_count: 0,
        sis_assignment_id: null,
        integration_id: null,
        integration_data: {},
        quiz_id: 1,
        anonymous_submissions: false,
        published: true,
        unpublishable: false,
        only_visible_to_overrides: false,
        locked_for_user: false,
        submissions_download_url:
            'http://sdlstudentvm06.msoe.edu/courses/1/quizzes/1/submissions?zip=1',
        post_manually: false,
        anonymize_students: false,
        require_lockdown_browser: false,
        restrict_quantitative_data: false,
    }

    test('getQuiz Test', async () => {
        const response = await getQuiz({
            canvasAccessToken: 'Fake Token',
            canvasDomain: 'http://sdlstudentvm06.msoe.edu',
            courseId: 1,
            quizId: 4,
        })
        expect(response).toEqual(quizJSONList)
    })
})

describe('Testing quizSubmissions', async () => {
    const quizSubmissionJSONList = {
        id: 2,
        quiz_id: 1,
        quiz_version: 4,
        user_id: 2,
        submission_id: 4,
        score: 1.0,
        kept_score: 1.0,
        started_at: '2023-09-20T17:41:07Z',
        end_at: null,
        finished_at: '2023-09-21T03:39:56Z',
        attempt: 1,
        workflow_state: 'pending_review',
        fudge_points: 0.0,
        quiz_points_possible: 1.0,
        extra_attempts: null,
        extra_time: null,
        manually_unlocked: null,
        validation_token:
            '20ed1d6a96f5c85b73b979ddd2af7d4d29e3aad0df4ef277845cb643d679ea86',
        score_before_regrade: null,
        has_seen_results: false,
        time_spent: 35929,
        attempts_left: 0,
        overdue_and_needs_submission: false,
        'excused?': false,
        html_url:
            'http://sdlstudentvm06.msoe.edu/courses/1/quizzes/1/submissions/2',
        result_url:
            'http://sdlstudentvm06.msoe.edu/courses/1/quizzes/1/history?quiz_submission_id=2\u0026version=1',
    }

    test('quizSubmissions Test', async () => {
        const response = await getQuizSubmission({
            canvasAccessToken: 'Fake Token',
            canvasDomain: 'http://sdlstudentvm06.msoe.edu',
            courseId: 1,
            quizId: 1,
            submissionId: 4,
        })
        expect(response).toEqual(quizSubmissionJSONList)
    })
})
