variables:
  DESKTOP_BASE_PATH: apps/desktop

install-desktop:
  image: $CI_REGISTRY_IMAGE/desktop:latest
  stage: 🛞 install
  script:
    - cd $DESKTOP_BASE_PATH
    - npm ci
  artifacts:
    paths:
      - $DESKTOP_BASE_PATH/node_modules/

test-desktop:
  image: $CI_REGISTRY_IMAGE/desktop:latest
  stage: 🤞 test
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - $DESKTOP_BASE_PATH/junit.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build-desktop:
  image: $CI_REGISTRY_IMAGE/desktop:latest
  stage: 📦 build
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run build
  artifacts:
    paths:
      - $DESKTOP_BASE_PATH/build/
      - $DESKTOP_BASE_PATH/.svelte-kit/

release-desktop:
  image: $CI_REGISTRY_IMAGE/desktop:latest
  stage: 🚀 release
  needs: ['install-desktop', 'build-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run tauri build
  artifacts:
    paths:
      - $DESKTOP_BASE_PATH/src-tauri/target/release/
