image: node:18

stages:
  - install
  - test
  - build
  - release

variables:
  DESKTOP_BASE_PATH: apps/desktop

install-desktop:
  stage: install
  script:
    - cd $DESKTOP_BASE_PATH
    - npm ci
  artifacts:
    paths:
      - $DESKTOP_BASE_PATH/node_modules/

test-desktop:
  stage: test
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run test
  artifacts:
    when: always
    reports:
      junit:
        - $DESKTOP_BASE_PATH/junit.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build-desktop:
  stage: build
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run build
  artifacts:
    paths:
      - $DESKTOP_BASE_PATH/build/

release-desktop:
  stage: release
  needs: ['install-desktop', 'build-desktop']
  before_script:
    - apt-get install -y curl
    - curl https://sh.rustup.rs -sSf | sh -y
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run tauri build
  artifacts:
    paths:
      - $DESKTOP_BASE_PATH/src-tauri/target/release/
