image: node:18

stages:
  - install
  - test
  - build
  - release

variables:
  DESKTOP_BASE_PATH: apps/desktop

cache:
  paths:
    - $DESKTOP_BASE_PATH/node_modules/

install-desktop:
  stage: install
  script:
    - cd $DESKTOP_BASE_PATH
    - npm ci

test-desktop:
  stage: test
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run test
  artifacts:
    when: always
    reports:
      junit:
        - $BASE_PATH/junit.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build-desktop:
  stage: build
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run build
  artifacts:
    paths:
      - $BASE_PATH/build/

release-desktop:
  stage: release
  needs:
    - job: build-desktop
      artifacts: true
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run tauri build
  artifacts:
    paths:
      - $BASE_PATH/src-tauri/target/release/
