image: node:18

stages:
  - install
  - test
  - build
  - release

variables:
  DESKTOP_BASE_PATH: apps/desktop

install-desktop:
  stage: install
  script:
    - cd $DESKTOP_BASE_PATH
    - npm ci
  cache:
    paths:
      - $DESKTOP_BASE_PATH/node_modules/

test-desktop:
  stage: test
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run test
  artifacts:
    when: always
    reports:
      junit:
        - $BASE_PATH/junit.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build-desktop:
  stage: build
  needs: ['install-desktop']
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run build
  artifacts:
    paths:
      - $BASE_PATH/build/

release-desktop:
  stage: release
  needs:
    - job: build-desktop
      artifacts: true
  before_script:
    - apt-get update && apt-get install -y curl
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
    - sh ./sh.rustup.rs
  script:
    - cd $DESKTOP_BASE_PATH
    - npm run tauri build
  artifacts:
    paths:
      - $BASE_PATH/src-tauri/target/release/
