install-desktop:
  image: node:18
  stage: 🛞 install
  needs:
    - job: build-docker-desktop
      optional: true
  script:
    - cd apps/desktop/
    - npm ci
  artifacts:
    paths:
      - apps/desktop/node_modules/

test-desktop:
  image: node:18
  stage: 🤞 test
  needs: ['install-desktop']
  script:
    - cd apps/desktop/
    - npm run coverage
  artifacts:
    when: always
    reports:
      junit:
        - apps/desktop/junit.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

release-desktop-linux:
  image: electronuserland/builder:latest
  stage: 🚀 release
  needs: ['install-desktop']
  script:
    - cd apps/desktop/
    - npm run build:linux
  artifacts:
    paths:
      - apps/desktop/dist/
  when: manual

release-desktop-windows:
  image: electronuserland/builder:latest
  stage: 🚀 release
  needs: ['install-desktop']
  script:
    - cd apps/desktop/
    - npm run build:win
  artifacts:
    paths:
      - apps/desktop/dist/
  when: manual

release-desktop-mac:
  image: electronuserland/builder:latest
  stage: 🚀 release
  needs: ['install-desktop']
  script:
    - cd apps/desktop/
    - npm run build:mac
  artifacts:
    paths:
      - apps/desktop/dist/
  when: manual
