image: node:18

stages:
    - install
    - test
    - build
    - release

variables:
    BASE_PATH: apps/cli

cache:
    paths:
        - $BASE_PATH/node_modules/

before_script:
    - cd $BASE_PATH/

install-cli:
    stage: install
    script:
        - npm ci

test-format-cli:
    stage: test
    needs: ['install-cli']
    script:
        - npm run format:check

test-cli:
    stage: test
    needs: ['install-cli']
    script:
        - npm run test:ci
    artifacts:
        when: always
        reports:
            junit:
                - $BASE_PATH/junit.xml
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

test-pandoc-linux:
    image:
        name: pandoc/core
        entrypoint: ['/bin/sh', '-c']
    stage: test
    needs: ['install-cli']
    script:
        - pandoc --version
        - npm run test:pandoc-linux

build-cli:
    stage: build
    needs: ['install-cli']
    script:
        - npm run build
    artifacts:
        paths:
            - $BASE_PATH/build/

release-cli:
    stage: release
    needs:
        - job: build-cli
          artifacts: true
    script:
        - npm run package:win-x64
    artifacts:
        paths:
            - $BASE_PATH/release/
