install-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 🛞 install
    needs:
        - job: build-docker-cli
          optional: true
    script:
        - cd $CLI_BASE_PATH/
        - npm ci
    artifacts:
        paths:
            - $CLI_BASE_PATH/node_modules/

test-format-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 🤞 test
    needs: ['install-cli']
    script:
        - cd $CLI_BASE_PATH/
        - npm run format:check

test-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 🤞 test
    needs: ['install-cli']
    script:
        - cd $CLI_BASE_PATH/
        - npm run test:ci
    artifacts:
        when: always
        reports:
            junit:
                - $CLI_BASE_PATH/junit.xml
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 📦 build
    needs: ['install-cli']
    script:
        - cd $CLI_BASE_PATH/
        - npm run build
    artifacts:
        paths:
            - $CLI_BASE_PATH/build/

release-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 🚀 release
    needs: ['install-cli', 'build-cli']
    script:
        - cd $CLI_BASE_PATH/
        - npm run package:win-x64
    artifacts:
        paths:
            - $CLI_BASE_PATH/release/
    when: manual
