image: node:18

stages:
  - build
  - release

variables:
  BASE_PATH: apps/cli

cache:
  paths:
    - $BASE_PATH/node_modules/

before_script:
  - cd $BASE_PATH/

build-cli:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - ./build/

release-cli:
  stage: release
  needs:
    - job: build-cli
      artifacts: true
  script:
    - npm run package:win-x64
  artifacts:
    paths:
      - ./release/
