image: node:18

stages:
    - install
    - test
    - build
    - release

variables:
    BASE_PATH: apps/cli

install-cli:
    stage: install
    script:
        - cd $BASE_PATH/
        - npm ci
    artifacts:
        paths:
            - $BASE_PATH/node_modules/

test-format-cli:
    stage: test
    needs: ['install-cli']
    script:
        - cd $BASE_PATH/
        - npm run format:check

test-cli:
    stage: test
    needs: ['install-cli']
    script:
        - cd $BASE_PATH/
        - npm run test:ci
    artifacts:
        when: always
        reports:
            junit:
                - $BASE_PATH/junit.xml
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build-cli:
    stage: build
    needs: ['install-cli']
    script:
        - cd $BASE_PATH/
        - npm run build
    artifacts:
        paths:
            - $BASE_PATH/build/

release-cli:
    stage: release
    needs: ['build-cli']
    script:
        - cd $BASE_PATH/
        - npm run package:win-x64
    artifacts:
        paths:
            - $BASE_PATH/release/
