image: node:18

stages:
  - build
  - test
  - release

variables:
  BASE_PATH: apps/cli

cache:
  paths:
    - $BASE_PATH/node_modules/

before_script:
  - cd $BASE_PATH/

install:
  stage: build
  script:
    - npm ci

build-cli:
  stage: build
  needs: ["install"]
  script:
    - npm run build
  artifacts:
    paths:
      - $BASE_PATH/build/

test-cli:
  stage: test
  needs: ["install"]
  script:
    - npm run test:ci
  reports:
    junit:
      - $BASE_PATH/junit.xml

release-cli:
  stage: release
  needs:
    - job: build-cli
      artifacts: true
  script:
    - npm run package:win-x64
  artifacts:
    paths:
      - $BASE_PATH/release/
