test-format-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 🤞 test
    needs: ['install-packages']
    script:
        - pnpm cli format:check

test-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 🤞 test
    needs: ['install-packages']
    script:
        - pnpm cli test:ci
    artifacts:
        when: always
        reports:
            junit:
                - $CLI_BASE_PATH/junit.xml
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

build-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 📦 build
    needs: ['install-packages']
    script:
        - pnpm cli build
    artifacts:
        paths:
            - $CLI_BASE_PATH/build/

release-cli:
    image: $CI_REGISTRY_IMAGE/cli:latest
    stage: 🚀 release
    needs: ['install-packages', 'build-cli']
    script:
        - pnpm cli package:win-x64
    artifacts:
        paths:
            - $CLI_BASE_PATH/release/
    when: manual
