test-@canvas-capture:
    image: $BASE_IMAGE
    stage: 🤞 test
    needs: ['install-packages']
    script:
        - pnpm @canvas-capture coverage
    artifacts:
        when: always
        reports:
            junit:
                - canvas-capture/junit.xml
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

mutate-canvas-capture:
    image: $BASE_IMAGE
    stage: 🧬 mutant-test
    needs: ['install-packages', 'test-@canvas-capture']
    script:
        - pnpm @canvas-capture test:mutate
    artifacts:
        paths:
            - canvas-capture/reports/mutation/mutation.html
    rules:
        - if: $CI_COMMIT_TAG
          when: always
        - when: manual
          allow_failure: true
